name: 'ChatGPT PR Review Action'
description: 'Use ChatGPT to Review Pull Request.'
author: wxul
inputs:
  language:
    description: Language
    default: English
    required: false

  tech_stack:
    description: Tech stack list
    required: false

  custom_system:
    description: Custom ChatGPT system message
    required: false

  override_prompt:
    description: Override default ChatGPT review prompt, inputs of language and tech_stack will not work
    required: false

  model:
    description: ChatGPT model
    default: gpt-3.5-turbo
    required: false

  max_token:
    description: ChatGPT max token, default is 2000
    default: '2000'
    required: false

  include:
    description: Include files
    required: true

  filter_with_label:
    description: Only review with specific label if set
    required: false

runs:
  using: 'node16'
  main: 'lib/index.js'
